# Remove the version field - it's obsolete in modern Docker Compose
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:3001
      - NODE_ENV=production
    depends_on:
      - backend
    volumes:
      - ./public/ugc:/app/public/ugc
    networks:
      - app-network
    restart: unless-stopped
    # Add resource limits to prevent memory issues
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - NODE_ENV=production
    volumes:
      - ./backend/src:/app/src
      - ./public/ugc:/app/public/ugc
    networks:
      - app-network
    restart: unless-stopped
    # Add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  app-network:
    driver: bridge